### PR TITLE
Use the new FQDN for our dashboard.

### PR DESCRIPTION
**Pull request by puck**

### CODE REVIEW

**Comment by adrianjarvis** [comment]
Please do not merge this until we have made changes to the DNS..... the new DNS name is a CNAME with a TTL of 1 hour so we need to get it changed to have a lower TTL and be an A record before directing customers to use it.

**Comment by adrianjarvis** [comment]
I had forgotten about this pull request and have done the changes in my PR to update all of the broken external links.

**Comment by vaudelbenoit** [comment]
I believe this PR can be closed. @adrianjarvis do you agree?

**Comment by adrianjarvis** [comment]
See this PR can be closed.

**Comment by adrianjarvis** [comment]
Nothing left to merge

**Pull request closed without merging**
