### PR TITLE
Update links to dashboard to use dashboard.catalystcloud.nz

### PR DESCRIPTION
**Pull request by vaudelbenoit**
Update links to Dashboard from dashboard.cloud.catalyst.net.nz to dashboard.catalystcloud.nz

### CODE REVIEW

**Comment by adrianjarvis** [comment]
I've done this too.

**Comment by adrianjarvis** [comment]
Dan merge my change so hopefully this one is now redundant.

**Comment by vaudelbenoit** [comment]
Sweet.
I solved the conflicts and there's no change anymore, so I'm going to close it.

**Comment by vaudelbenoit** [comment]
Redundant.

**Pull request closed without merging**
