### PR TITLE
Improve autohealing example with region agnostic template

### PR DESCRIPTION
**Pull request by iokiwi**
Depends on: https://github.com/catalyst-cloud/catalystcloud-orchestration/pull/1

Please merge the linked pull request first as it contains resources referenced and depended on by this pull request.

### CODE REVIEW

**Comment by danielobyrne** [comment]
Waiting to create tutorial section to put this change in there. Will adapt things from this change to main documentation however

**Comment by iokiwi** [comment]
I'm not sure I really understand, as it is exactly the same content tidied up and optimized. The preformetted text field that this replaces was just the scratch notes the devs were using during development low level testing are minimal,  and optimized for our convenience, not the understanding of the customer. Just my opinion.

**Comment by danielobyrne** [comment]
The reason I want to hold off on this merge is because the use case for the basic user who would be reading the documentation would not be served by the new script. 
Most likely users will not want to incur costs from creating an entirely new network just to test the functionality of the alarm service. So I will change the current documentation taking some ideas from the proposed changes. 
But as for the use of the new scripts; we want to put them and this page for their use in the "additional tutorials" section of the documentation, rather than replace the main example.

**Comment by iokiwi** [comment]
I appreciate your position and I think a tutorial section would be good. 

Note the cost of a network for one hour is `$0.02` compared with the total of around `$0.13` for  all the resources including `$0.08` of compute and `$0.03` for the loadbalancer.  In my opinion, `$0.13` is negligible compared to the cost of any production workloads and for users who have 

- our billing system writes of cha

the convenience and piece of mind of knowing that everything is configured exactly as it should be for the example to work far outweighs the `$0.03` difference in charges.

All resources created from the stack template, including the network, will get deleted automatically when the stack is deleted.

**Pull request closed without merging**
